import type { Meal } from "@/lib/meals";

export const HOUSEHOLD: Meal[] = [
  {
    id: "taco-soup",
    name: "Taco soup",
    cuisine: "American",
    minutes: 30,
    servings: 6,
    effort: "Easy",
    tags: ["soup", "kid-friendly", "high-protein"],
    household: true,
    summary: "Ground beef, beans, corn, and taco seasoning. Chips and cheddar on top.",
    ingredients: [
      { name: "Ground beef", amount: 1, unit: "lb", aisle: "Protein" },
      { name: "Yellow onion", amount: 1, unit: "", aisle: "Produce" },
      { name: "Black beans (15 oz)", amount: 1, unit: "can", aisle: "Pantry" },
      { name: "Corn (15 oz)", amount: 1, unit: "can", aisle: "Pantry" },
      { name: "Diced tomatoes with green chiles (10 oz)", amount: 1, unit: "can", aisle: "Pantry" },
      { name: "Tomato sauce (8 oz)", amount: 1, unit: "can", aisle: "Pantry" },
      { name: "Beef broth", amount: 2, unit: "cup", aisle: "Pantry" },
      { name: "Chili powder", amount: 1, unit: "tbsp", aisle: "Spices" },
      { name: "Ground cumin", amount: 2, unit: "tsp", aisle: "Spices" },
      { name: "Tortilla chips", amount: 2, unit: "cup", aisle: "Pantry" },
      { name: "Shredded cheddar", amount: 4, unit: "oz", aisle: "Dairy" },
      { name: "Sour cream", amount: 0.5, unit: "cup", aisle: "Dairy" },
    ],
    steps: [
      "Brown the beef with the chopped onion. Drain the fat.",
      "Stir in the beans, corn, tomatoes, tomato sauce, broth, chili powder, and cumin.",
      "Simmer 15 minutes. Salt if it needs it.",
      "Bowl it with chips, cheddar, and sour cream.",
    ],
  },
  {
    id: "texas-chili",
    name: "Texas chili",
    cuisine: "American",
    minutes: 75,
    servings: 6,
    effort: "Steady",
    tags: ["soup", "high-protein"],
    household: true,
    summary: "Cubed beef and dried chiles. No beans.",
    ingredients: [
      { name: "Beef chuck", amount: 2, unit: "lb", aisle: "Protein" },
      { name: "Yellow onion", amount: 1, unit: "", aisle: "Produce" },
      { name: "Garlic", amount: 4, unit: "clove", aisle: "Produce" },
      { name: "Beef broth", amount: 2, unit: "cup", aisle: "Pantry" },
      { name: "Chili powder", amount: 3, unit: "tbsp", aisle: "Spices" },
      { name: "Ground cumin", amount: 1, unit: "tbsp", aisle: "Spices" },
      { name: "Dried oregano", amount: 1, unit: "tsp", aisle: "Spices" },
      { name: "Crushed tomatoes (14 oz)", amount: 1, unit: "can", aisle: "Pantry" },
    ],
    steps: [
      "Cut the chuck into bite-size cubes and season with salt and pepper.",
      "Brown the beef in batches. Soften the onion and garlic in the same pot.",
      "Return the beef. Add chili powder, cumin, oregano, tomatoes, and broth.",
      "Simmer until the beef is tender, about an hour. Add a splash of water if it gets too thick.",
    ],
  },
  {
    id: "beef-chili",
    name: "Beef chili",
    cuisine: "American",
    minutes: 45,
    servings: 6,
    effort: "Easy",
    tags: ["soup", "kid-friendly", "high-protein"],
    household: true,
    summary: "Ground beef and beans in a tomato chili. The weeknight pot.",
    ingredients: [
      { name: "Ground beef", amount: 1.5, unit: "lb", aisle: "Protein" },
      { name: "Yellow onion", amount: 1, unit: "", aisle: "Produce" },
      { name: "Garlic", amount: 3, unit: "clove", aisle: "Produce" },
      { name: "Kidney beans (15 oz)", amount: 2, unit: "can", aisle: "Pantry" },
      { name: "Diced tomatoes (14 oz)", amount: 1, unit: "can", aisle: "Pantry" },
      { name: "Tomato paste", amount: 2, unit: "tbsp", aisle: "Pantry" },
      { name: "Beef broth", amount: 1, unit: "cup", aisle: "Pantry" },
      { name: "Chili powder", amount: 2, unit: "tbsp", aisle: "Spices" },
      { name: "Ground cumin", amount: 1, unit: "tbsp", aisle: "Spices" },
      { name: "Shredded cheddar", amount: 4, unit: "oz", aisle: "Dairy" },
    ],
    steps: [
      "Brown the beef with the onion and garlic. Drain the fat.",
      "Stir in the tomato paste, chili powder, and cumin.",
      "Add the tomatoes, drained beans, and broth. Simmer 25 minutes.",
      "Serve with cheddar.",
    ],
  },
  {
    id: "zuppa-toscana",
    name: "Zuppa Toscana",
    cuisine: "Italian",
    minutes: 40,
    servings: 6,
    effort: "Easy",
    tags: ["soup", "high-protein"],
    household: true,
    summary: "Italian sausage, potatoes, kale, and a little cream.",
    ingredients: [
      { name: "Italian sausage", amount: 1, unit: "lb", aisle: "Protein" },
      { name: "Yellow onion", amount: 1, unit: "", aisle: "Produce" },
      { name: "Garlic", amount: 3, unit: "clove", aisle: "Produce" },
      { name: "Russet potato", amount: 3, unit: "", aisle: "Produce" },
      { name: "Chicken broth", amount: 6, unit: "cup", aisle: "Pantry" },
      { name: "Kale", amount: 4, unit: "cup", aisle: "Produce" },
      { name: "Heavy cream", amount: 0.75, unit: "cup", aisle: "Dairy" },
    ],
    steps: [
      "Brown the sausage, breaking it up. Add the chopped onion and garlic.",
      "Add the broth and the potatoes, sliced into half-moons. Simmer until the potatoes are tender.",
      "Stir in the kale and cream. Heat through without boiling.",
      "Salt and pepper.",
    ],
  },
  {
    id: "italian-sausage-ditalini",
    name: "Italian sausage ditalini",
    cuisine: "Italian",
    minutes: 30,
    servings: 4,
    effort: "Easy",
    tags: ["one-pan", "kid-friendly"],
    household: true,
    summary: "Sausage and little pasta in a tomato pot, finished with Parmesan.",
    ingredients: [
      { name: "Italian sausage", amount: 1, unit: "lb", aisle: "Protein" },
      { name: "Ditalini", amount: 12, unit: "oz", aisle: "Pantry" },
      { name: "Crushed tomatoes (28 oz)", amount: 1, unit: "can", aisle: "Pantry" },
      { name: "Chicken broth", amount: 3, unit: "cup", aisle: "Pantry" },
      { name: "Yellow onion", amount: 1, unit: "", aisle: "Produce" },
      { name: "Garlic", amount: 3, unit: "clove", aisle: "Produce" },
      { name: "Baby spinach", amount: 2, unit: "cup", aisle: "Produce" },
      { name: "Parmesan", amount: 2, unit: "oz", aisle: "Dairy" },
    ],
    steps: [
      "Brown the sausage with the chopped onion and garlic.",
      "Add the tomatoes and broth. Bring it to a simmer and stir in the ditalini.",
      "Cook until the pasta is tender, about 12 minutes, adding a splash of water if it sticks.",
      "Wilt in the spinach. Top with Parmesan.",
    ],
  },
  {
    id: "one-pot-spaghetti",
    name: "One pot spaghetti",
    cuisine: "American",
    minutes: 30,
    servings: 4,
    effort: "Easy",
    tags: ["one-pan", "kid-friendly"],
    household: true,
    summary: "Beef, spaghetti, and sauce cooked in the same pot.",
    ingredients: [
      { name: "Ground beef", amount: 1, unit: "lb", aisle: "Protein" },
      { name: "Spaghetti", amount: 12, unit: "oz", aisle: "Pantry" },
      { name: "Crushed tomatoes (28 oz)", amount: 1, unit: "can", aisle: "Pantry" },
      { name: "Beef broth", amount: 3, unit: "cup", aisle: "Pantry" },
      { name: "Yellow onion", amount: 1, unit: "", aisle: "Produce" },
      { name: "Garlic", amount: 3, unit: "clove", aisle: "Produce" },
      { name: "Italian seasoning", amount: 1, unit: "tsp", aisle: "Spices" },
      { name: "Parmesan", amount: 2, unit: "oz", aisle: "Dairy" },
    ],
    steps: [
      "Brown the beef with the onion and garlic. Drain the fat.",
      "Add the tomatoes, broth, and Italian seasoning. Break the spaghetti in half and press it into the pot.",
      "Simmer, stirring now and then, until the pasta is tender, about 15 minutes.",
      "Toss with Parmesan.",
    ],
  },
  {
    id: "spaghetti",
    name: "Spaghetti",
    cuisine: "Italian",
    minutes: 35,
    servings: 4,
    effort: "Easy",
    tags: ["kid-friendly"],
    household: true,
    summary: "Noodles and a simple meat sauce. The regular one.",
    ingredients: [
      { name: "Spaghetti", amount: 1, unit: "lb", aisle: "Pantry" },
      { name: "Ground beef", amount: 1, unit: "lb", aisle: "Protein" },
      { name: "Crushed tomatoes (28 oz)", amount: 1, unit: "can", aisle: "Pantry" },
      { name: "Yellow onion", amount: 1, unit: "", aisle: "Produce" },
      { name: "Garlic", amount: 3, unit: "clove", aisle: "Produce" },
      { name: "Tomato paste", amount: 2, unit: "tbsp", aisle: "Pantry" },
      { name: "Italian seasoning", amount: 1, unit: "tsp", aisle: "Spices" },
      { name: "Parmesan", amount: 2, unit: "oz", aisle: "Dairy" },
    ],
    steps: [
      "Boil the spaghetti in salted water.",
      "Brown the beef with the onion and garlic. Stir in the tomato paste and Italian seasoning.",
      "Add the tomatoes and simmer 15 minutes.",
      "Toss the pasta with the sauce. Serve with Parmesan.",
    ],
  },
  {
    id: "bolognese",
    name: "Bolognese",
    cuisine: "Italian",
    minutes: 60,
    servings: 6,
    effort: "Steady",
    tags: ["high-protein"],
    household: true,
    summary: "A slow meat sauce with milk and tomato, on pasta.",
    ingredients: [
      { name: "Ground beef", amount: 1, unit: "lb", aisle: "Protein" },
      { name: "Ground pork", amount: 0.5, unit: "lb", aisle: "Protein" },
      { name: "Yellow onion", amount: 1, unit: "", aisle: "Produce" },
      { name: "Carrot", amount: 1, unit: "", aisle: "Produce" },
      { name: "Celery", amount: 1, unit: "stalk", aisle: "Produce" },
      { name: "Garlic", amount: 2, unit: "clove", aisle: "Produce" },
      { name: "Whole milk", amount: 0.5, unit: "cup", aisle: "Dairy" },
      { name: "Crushed tomatoes (28 oz)", amount: 1, unit: "can", aisle: "Pantry" },
      { name: "Tomato paste", amount: 2, unit: "tbsp", aisle: "Pantry" },
      { name: "Spaghetti", amount: 1, unit: "lb", aisle: "Pantry" },
      { name: "Parmesan", amount: 2, unit: "oz", aisle: "Dairy" },
    ],
    steps: [
      "Soften the chopped onion, carrot, and celery in a little oil. Add the garlic.",
      "Brown the beef and pork in the pot. Pour in the milk and let it cook down.",
      "Stir in the tomato paste and tomatoes. Simmer 40 minutes, uncovered.",
      "Boil the spaghetti and toss it with the sauce and Parmesan.",
    ],
  },
  {
    id: "steak",
    name: "Steak",
    cuisine: "American",
    minutes: 50,
    servings: 4,
    effort: "Easy",
    tags: ["high-protein"],
    household: true,
    summary: "Pan-seared steak, baked potatoes, and a green salad.",
    ingredients: [
      { name: "Steak", amount: 1.5, unit: "lb", aisle: "Protein" },
      { name: "Russet potato", amount: 4, unit: "", aisle: "Produce" },
      { name: "Butter", amount: 2, unit: "tbsp", aisle: "Dairy" },
      { name: "Garlic", amount: 2, unit: "clove", aisle: "Produce" },
      { name: "Romaine", amount: 1, unit: "head", aisle: "Produce" },
      { name: "Sour cream", amount: 0.5, unit: "cup", aisle: "Dairy" },
    ],
    steps: [
      "Heat the oven to 425°F. Scrub the potatoes, oil them, and bake until tender, about 45 minutes. Start them first.",
      "Salt the steak and let it sit while the pan gets hot.",
      "Sear the steak in a little oil. Add the butter and garlic for the last minute. Rest 5 minutes.",
      "Salad on the side. Potatoes with butter and sour cream.",
    ],
  },
  {
    id: "hamburgers",
    name: "Hamburgers",
    cuisine: "American",
    minutes: 25,
    servings: 4,
    effort: "Easy",
    tags: ["quick", "kid-friendly", "high-protein"],
    household: true,
    summary: "Beef patties, buns, and the usual toppings.",
    ingredients: [
      { name: "Ground beef", amount: 1.5, unit: "lb", aisle: "Protein" },
      { name: "Hamburger buns", amount: 4, unit: "", aisle: "Bakery" },
      { name: "Cheddar slices", amount: 4, unit: "", aisle: "Dairy" },
      { name: "Lettuce", amount: 1, unit: "head", aisle: "Produce" },
      { name: "Tomato", amount: 1, unit: "", aisle: "Produce" },
      { name: "Yellow onion", amount: 1, unit: "", aisle: "Produce" },
      { name: "Pickles", amount: 1, unit: "", aisle: "Pantry" },
    ],
    steps: [
      "Divide the beef into four patties, a little wider than the buns. Salt and pepper both sides.",
      "Cook in a hot pan, about 4 minutes a side. Add cheese for the last minute.",
      "Toast the buns.",
      "Build them with lettuce, tomato, onion, and pickles.",
    ],
  },
];
